name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2022-10-28
version: '10.0.0-beta2+131-dev'
project: 'drupal'
datestamp: 1666961462
