name: Testing config overrides
type: profile
description: 'Minimal profile for running tests with config overrides in a profile.'
# version: VERSION
# This profile is copied to a non-core location by
# \Drupal\Tests\config\Functional\ConfigInstallProfileUnmetDependenciesTest.
core_version_requirement: '*'
hidden: true
install:
  - action
  - language
  - testing_config_overrides_module
  - tour

# Information added by Drupal.org packaging script on 2022-10-28
version: '10.0.0-beta2+131-dev'
project: 'drupal'
datestamp: 1666961461
